### ISSUE TITLE
Payment 

### ISSUE THREAD

**Issue by mishravk79** [bywatersolutions/koha-offline-circulation#3]
Hello

May i know how to pay fines in offline mode and upload later like issue/return? I have tried but seems its not working, the file created contains all the fields except barcode during payment of fines. Barcode is also mandatory if yes then how to add barcode against the fines.

Thanking You

**Comment by kylemhall** [comment]
Payments though the offline circulation client are "pay by amount" where Koha pays off fines from oldest to newest. You should not need to enter an item barcode to log a payment.

**Comment by mishravk79** [comment]
Hello

Thanks for your email, but when I attempt to import the data into the
testing machine, nothing happens like processed 100% which is working fine
in issue/return.

May I know what may be the issue, I am testing on koha 20.05

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by kylemhall** [comment]
We haven't changed the offline circ code in 6 years. My bet is that this is a bug in Koha itself.

Can you post the contents of the .koc file you are uploading?

**Comment by mishravk79** [comment]
Let me check once more, maybe my test environment is not correct. Will
update you soon.

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by mishravk79** [comment]
Hello

Seems it's working the error seems to be due to some illogical data
transfer by me. Actually, I wish to migrate bulk transaction history with
the help of this module. I have tested and found sequencing needs to be
maintained i.e. the date/time on which transaction was done should be in
increasing order.

Below is data manipulated by me but seems the order in which it is written
same is not maintained while importing i.e. "return" comes first then issue.

I wish to make a framework that should work while uploading data in bulk
(migration). Can you explain these *" 2021-09-01 00-00-00 000" figures here
may be data, time and last three digits I don't know. *

Version=1.0 Generator=kocDesktop GeneratorVersion=1.3
2021-09-01 00-00-00 000 issue 2131074 5555
2021-09-01 00-00-00 000 issue 2131075 77777
2021-09-01 00-00-00 000 return 77776
2021-09-01 00-00-00 000 return 80000

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by kylemhall** [comment]
The "000" would be milliseconds of the timestamp. Have you read the file format specification?

https://wiki.koha-community.org/wiki/Koha_offline_circulation_file_format

**Comment by mishravk79** [comment]
Hello

Thanks for your prompt reply and link. I guess the file will be sorted with
a date then timestamp at the time of data import?
So if I will try to manipulate for ease of work like the below example
system will get confused and data will not be in proper order?
The book which is issued/return from the system must appear first in
datasheet (column) along with the date/time stamp so that if there are many
entries in a single date then the time stamp system can read first which
one to consider? Please help and confirm.

2021-09-01 00-00-00 000 issue 2131074 5555
2021-09-01 00-00-00 000 issue 2131075 77777
2021-09-01 00-00-00 000 return 77776
2021-09-01 00-00-00 000 return 80000

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by kylemhall** [comment]
Yes, that looks correct.

**Comment by mishravk79** [comment]
Hello

Sorry for an opening against this but I encounter a problem, the sample
data is shown below for your reference. The data in the framework does not
appear in the same order while importing. This may lead to data loss I have
manually assigned time however the date is the same as our original source.
Please help me to know the issue and the correct way to retain the order.

Thanking you once more

Sample date

Version=1.0 Generator=kocDesktop GeneratorVersion=1.3
2017-05-11 10-30-40 101 issue 2131074 71011
2017-05-11 10-30-40 102 return 71028
2017-05-11 10-30-40 103 issue 2131076 68818
2017-05-11 10-30-40 104 return 68818
2017-05-11 10-30-40 105 return 71011
2017-05-11 10-30-40 106 return 66318
2017-05-12 10-30-40 101 issue 2131074 37951
2017-05-12 10-30-40 102 issue 2131080 65882

Data serial number in Koha.

[image: image.png]


With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by mishravk79** [comment]
Sorry but please check if I uploaded the same file three times then out of
3 attempts first one chronology is correct but 2 is wrong but again the
fourth time its chronology appears correct in order as in the file.

It seems to be wrong some bug or I don't know why the system behaves in
this way.

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
URL: http://vinod.itshelp.co.in/
ORCID ID: http://orcid.org/0000-0003-4666-7874
Scopus ID: 57223138343

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*
